/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationDto { 
    deceasedFirstName?: string;
    deceasedLastName?: string;
    deceasedMiddleName?: string;
    deceasedOccupation?: string;
    deceasedAddress?: string;
    deceasedbusstop?: string;
    deceasedLandmark?: string;
    deathDate?: string;
    buriedDate?: string;
    hospital?: string;
    applicantFirstName?: string;
    applicantLastName?: string;
    applicantOccupation?: string;
    relationship?: string;
    applicantPhonenumber?: string;
    alternateNumber?: string;
    applicationId?: string;
    paymentStatus?: ApplicationDto.PaymentStatusEnum;
    approvalStatus?: ApplicationDto.ApprovalStatusEnum;
    timeCreated?: string;
}
export namespace ApplicationDto {
    export type PaymentStatusEnum = 'PAID' | 'PENDING' | 'NOT_PAID';
    export const PaymentStatusEnum = {
        Paid: 'PAID' as PaymentStatusEnum,
        Pending: 'PENDING' as PaymentStatusEnum,
        NotPaid: 'NOT_PAID' as PaymentStatusEnum
    };
    export type ApprovalStatusEnum = 'APPROVED' | 'REJECTED' | 'PENDING' | 'QUERIED';
    export const ApprovalStatusEnum = {
        Approved: 'APPROVED' as ApprovalStatusEnum,
        Rejected: 'REJECTED' as ApprovalStatusEnum,
        Pending: 'PENDING' as ApprovalStatusEnum,
        Queried: 'QUERIED' as ApprovalStatusEnum
    };
}


