/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Users } from './users';


export interface DeathApplications { 
    id?: number;
    dateDeactivated?: string;
    status?: DeathApplications.StatusEnum;
    deactivatedBy?: Users;
    lastUpdatedBy?: Users;
    createdBy?: Users;
    createdAt?: string;
    lastUpdatedAt?: string;
    deceasedFirstName?: string;
    deceasedLastName?: string;
    deceasedMiddleName?: string;
    deceasedOccupation?: string;
    deceasedAddress?: string;
    deceasedbusstop?: string;
    deceasedLandmark?: string;
    deathDate?: string;
    buriedDate?: string;
    hospital?: string;
    applicantFirstName?: string;
    applicantLastName?: string;
    applicantOccupation?: string;
    relationship?: string;
    applicantPhonenumber?: string;
    reason?: string;
    alternateNumber?: string;
    applicationId?: string;
    approvalStatus?: DeathApplications.ApprovalStatusEnum;
    paymentStatus?: DeathApplications.PaymentStatusEnum;
}
export namespace DeathApplications {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Inactive: 'INACTIVE' as StatusEnum
    };
    export type ApprovalStatusEnum = 'APPROVED' | 'REJECTED' | 'PENDING' | 'QUERIED';
    export const ApprovalStatusEnum = {
        Approved: 'APPROVED' as ApprovalStatusEnum,
        Rejected: 'REJECTED' as ApprovalStatusEnum,
        Pending: 'PENDING' as ApprovalStatusEnum,
        Queried: 'QUERIED' as ApprovalStatusEnum
    };
    export type PaymentStatusEnum = 'PAID' | 'PENDING' | 'NOT_PAID';
    export const PaymentStatusEnum = {
        Paid: 'PAID' as PaymentStatusEnum,
        Pending: 'PENDING' as PaymentStatusEnum,
        NotPaid: 'NOT_PAID' as PaymentStatusEnum
    };
}


