/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { State } from './state';


export interface Lga { 
    id?: number;
    name?: string;
    code?: string;
    logo?: string;
    website?: string;
    lgaSlogan?: string;
    zoneFk?: string;
    state?: State;
    color?: string;
    banner?: string;
    appName?: string;
    contact?: string;
    alternate?: string;
    description?: string;
}

