/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarriageDto { 
    groomFirstName?: string;
    groomLastName?: string;
    groomMiddleName?: string;
    groomOccupation?: string;
    groomAddress?: string;
    groombusstop?: string;
    groomLandmark?: string;
    brideFirstName?: string;
    brideLastName?: string;
    brideMiddleName?: string;
    brideOccupation?: string;
    brideAddress?: string;
    bridebusstop?: string;
    brideLandmark?: string;
    marriageDate?: string;
    groomPhonenumber?: string;
    bridePhonenumber?: string;
    groomSignature?: string;
    brideSignature?: string;
    brideWitnessSignature?: string;
    groomWitnessSignature?: string;
    approvalStatus?: MarriageDto.ApprovalStatusEnum;
    paymentStatus?: MarriageDto.PaymentStatusEnum;
    applicationId?: string;
    timeCreated?: string;
    church?: string;
    weddingDate?: string;
    brideGender?: string;
    brideName?: string;
    brideParentAddress?: string;
    groomWitnessName?: string;
    groomParentAddress?: string;
    groomParentName?: string;
    churchAddress?: string;
    priest?: string;
}
export namespace MarriageDto {
    export type ApprovalStatusEnum = 'APPROVED' | 'REJECTED' | 'PENDING' | 'QUERIED';
    export const ApprovalStatusEnum = {
        Approved: 'APPROVED' as ApprovalStatusEnum,
        Rejected: 'REJECTED' as ApprovalStatusEnum,
        Pending: 'PENDING' as ApprovalStatusEnum,
        Queried: 'QUERIED' as ApprovalStatusEnum
    };
    export type PaymentStatusEnum = 'PAID' | 'PENDING' | 'NOT_PAID';
    export const PaymentStatusEnum = {
        Paid: 'PAID' as PaymentStatusEnum,
        Pending: 'PENDING' as PaymentStatusEnum,
        NotPaid: 'NOT_PAID' as PaymentStatusEnum
    };
}


