/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Country } from './country';


export interface State { 
    id?: number;
    name?: string;
    code?: string;
    logo?: string;
    website?: string;
    stateSlogan?: string;
    zoneFk?: string;
    country?: Country;
}

