/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    firstName?: string;
    lastName?: string;
    otherNames?: string;
    phoneNumber?: string;
    address?: string;
    photo?: string;
    email?: string;
    lga?: number;
    area?: number;
    state?: number;
    nin?: string;
    password?: string;
    role?: string;
    gender?: string;
    dob?: string;
}

